import Head from "next/head";
import Script from "next/script";
import React from "react";
import Hero from "./Hero";
import Projects from "./Projects";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Tarek Next </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-gradient-to-b flex flex-col">


        <main className="flex-1">
          <Hero />
          <Projects />
        </main>

        <footer className="px-8 py-12 border-t border-gray-800">
          <div className="px-8 font-medium text-center">
            <a href="https://github.com/andrejjurkin/create-tailwind-app">
              Create Tailwind
            </a>
          </div>
        </footer>
      </div>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  );
}
