import Head from "next/head";
import Script from "next/script";
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Projects from "./Projects";
import Info from "./Info";
import Certificate from './Certificate';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Tarek Next </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-gradient-to-b flex flex-col">


        <Header />
        <Hero />
        <Projects />
        <Info />
        <Certificate />


      </div>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  );
}
